// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Administrator
{
    public int Id { get; set; }

    public string PasswordHash { get; set; }

    public string Salt { get; set; }

    public bool IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? ModifiedBy { get; set; }

    public int CompanyId { get; set; }

    public DateTimeOffset? LastPasswordChangeDate { get; set; }

    public bool ForcePasswordReset { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public DateTimeOffset ModifiedDate { get; set; }

    public int? UserId { get; set; }

    public int? RoleId { get; set; }

    public virtual ICollection<AdminBranch> AdminBranches { get; set; } = new List<AdminBranch>();

    public virtual ICollection<AdminPermission> AdminPermissions { get; set; } = new List<AdminPermission>();

    public virtual Company Company { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}