// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class AdminLockerGroup
{
    public int Id { get; set; }

    public int AdminId { get; set; }

    public int LockerGroupId { get; set; }

    public virtual Administrator Admin { get; set; }

    public virtual LockerGroup LockerGroup { get; set; }
}