// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class AdminSession
{
    public int Id { get; set; }

    public int AdministratorId { get; set; }

    public DateTimeOffset LoginTimestamp { get; set; }

    public DateTimeOffset? LogoutTimestamp { get; set; }

    public string IpAddress { get; set; }
}