// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class AdminBranch
{
    public int Id { get; set; }

    public int AdministratorId { get; set; }

    public int BranchId { get; set; }

    public virtual Administrator Administrator { get; set; }

    public virtual Branch Branch { get; set; }
}