// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class BrainModule
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int? BranchId { get; set; }

    public int? GroupId { get; set; }

    public string IpAddress { get; set; }

    public string MacAddress { get; set; }

    public int Status { get; set; }

    public Guid? BrainUid { get; set; }

    public int? CompanyId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Company Company { get; set; }

    public virtual LockerGroup Group { get; set; }

    public virtual ICollection<Locker> Lockers { get; set; } = new List<Locker>();
}