// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Branch
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? CompanyId { get; set; }

    public int AddressId { get; set; }

    public int? Mode { get; set; }

    public string Comment { get; set; }

    public virtual ICollection<AdminBranch> AdminBranches { get; set; } = new List<AdminBranch>();

    public virtual ICollection<BrainModule> BrainModules { get; set; } = new List<BrainModule>();

    public virtual ICollection<BranchAddress> BranchAddresses { get; set; } = new List<BranchAddress>();

    public virtual ICollection<LockerGroup> LockerGroups { get; set; } = new List<LockerGroup>();

    public virtual ICollection<UserBranch> UserBranches { get; set; } = new List<UserBranch>();
}