// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Card
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string CardNumber { get; set; }
}