// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Company
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public int Country { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string CountryCode { get; set; }

    public Guid? AccountUid { get; set; }

    public string LockerTypeIds { get; set; }

    public virtual ICollection<Administrator> Administrators { get; set; } = new List<Administrator>();

    public virtual ICollection<BrainModule> BrainModules { get; set; } = new List<BrainModule>();
}