// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FurchaDAL.Models;

public partial class furchaContext : DbContext
{
    public furchaContext(DbContextOptions<furchaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminBranch> AdminBranches { get; set; }

    public virtual DbSet<AdminPermission> AdminPermissions { get; set; }

    public virtual DbSet<AdminSession> AdminSessions { get; set; }

    public virtual DbSet<Administrator> Administrators { get; set; }

    public virtual DbSet<BrainModule> BrainModules { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<BranchAddress> BranchAddresses { get; set; }

    public virtual DbSet<Card> Cards { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Locker> Lockers { get; set; }

    public virtual DbSet<LockerGroup> LockerGroups { get; set; }

    public virtual DbSet<ObjectType> ObjectTypes { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserBranch> UserBranches { get; set; }

    public virtual DbSet<UserEventLog> UserEventLogs { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<UserGroupBranch> UserGroupBranches { get; set; }

    public virtual DbSet<UserGroupLocker> UserGroupLockers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminBranch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminBra__3214EC075FBECB74");

            entity.ToTable("AdminBranch", "furcha");

            entity.HasOne(d => d.Administrator).WithMany(p => p.AdminBranches)
                .HasForeignKey(d => d.AdministratorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminBranch_Administrator");

            entity.HasOne(d => d.Branch).WithMany(p => p.AdminBranches)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminBranch_Branch");
        });

        modelBuilder.Entity<AdminPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminPer__3214EC077CC373BF");

            entity.ToTable("AdminPermission", "furcha");

            entity.HasOne(d => d.Administrator).WithMany(p => p.AdminPermissions)
                .HasForeignKey(d => d.AdministratorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminPermission_Administrator");

            entity.HasOne(d => d.Permission).WithMany(p => p.AdminPermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AdminPermission_Permission");
        });

        modelBuilder.Entity<AdminSession>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminSes__3214EC07EF5317EB");

            entity.ToTable("AdminSession", "furcha");
        });

        modelBuilder.Entity<Administrator>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Administ__3214EC075B3293FE");

            entity.ToTable("Administrator", "furcha");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.Salt).IsRequired();

            entity.HasOne(d => d.Company).WithMany(p => p.Administrators)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Administrators_Companies");

            entity.HasOne(d => d.Role).WithMany(p => p.Administrators)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_Administrators_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.Administrators)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Administrators_Users");
        });

        modelBuilder.Entity<BrainModule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BrainMod__3214EC073E8338C1");

            entity.ToTable("BrainModule", "furcha");

            entity.Property(e => e.MacAddress).HasMaxLength(20);
            entity.Property(e => e.Status).HasDefaultValue(1);

            entity.HasOne(d => d.Branch).WithMany(p => p.BrainModules)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_BrainModule_Branch");

            entity.HasOne(d => d.Company).WithMany(p => p.BrainModules)
                .HasForeignKey(d => d.CompanyId)
                .HasConstraintName("FK_BrainModule_Company");

            entity.HasOne(d => d.Group).WithMany(p => p.BrainModules)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("FK_BrainModule_LockerGroup");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Branch__3214EC0730FAF02C");

            entity.ToTable("Branch", "furcha");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<BranchAddress>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BranchAd__3214EC079C99BE12");

            entity.ToTable("BranchAddress", "furcha");

            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PostalCode).HasMaxLength(20);
            entity.Property(e => e.Street)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Branch).WithMany(p => p.BranchAddresses)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("FK_BranchAddress_Branch");
        });

        modelBuilder.Entity<Card>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Card__3214EC07DBCD2C66");

            entity.ToTable("Card", "furcha");

            entity.Property(e => e.CardNumber)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Company__3214EC0771181399");

            entity.ToTable("Company", "furcha");

            entity.Property(e => e.City).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Street).IsRequired();
        });

        modelBuilder.Entity<Locker>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Locker__3214EC07C0E881F5");

            entity.ToTable("Locker", "furcha");

            entity.Property(e => e.LockerType).IsRequired();
            entity.Property(e => e.Number).HasColumnType("numeric(18, 0)");

            entity.HasOne(d => d.Group).WithMany(p => p.Lockers)
                .HasForeignKey(d => d.GroupId)
                .HasConstraintName("FK_Locker_LockerGroup");
        });

        modelBuilder.Entity<LockerGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LockerGr__3214EC079755E503");

            entity.ToTable("LockerGroup", "furcha");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Branch).WithMany(p => p.LockerGroups)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_LockerGroup_Branch");
        });

        modelBuilder.Entity<ObjectType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ObjectTy__3214EC07404AEC1E");

            entity.ToTable("ObjectType", "furcha");

            entity.HasIndex(e => e.Name, "UQ__ObjectTy__737584F628B1E9DE").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Permissi__3214EC0700803616");

            entity.ToTable("Permission", "furcha");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ObjectType).WithMany(p => p.Permissions)
                .HasForeignKey(d => d.ObjectTypeId)
                .HasConstraintName("FK_Permission_ObjectType");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC072C7562E3");

            entity.ToTable("Role", "furcha");

            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.OpenName).IsRequired();
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RolePerm__3214EC077B4AEB08");

            entity.ToTable("RolePermission", "furcha");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePermissions_Permission");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RolePermissions_Role");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC073C522500");

            entity.ToTable("User", "furcha");

            entity.HasMany(d => d.Lockers).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserLocker",
                    r => r.HasOne<Locker>().WithMany()
                        .HasForeignKey("LockerId")
                        .HasConstraintName("FK__UserLocke__Locke__2A164134"),
                    l => l.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserLocke__UserI__29221CFB"),
                    j =>
                    {
                        j.HasKey("UserId", "LockerId").HasName("PK__UserLock__92838BF99D844136");
                        j.ToTable("UserLocker", "furcha");
                    });

            entity.HasMany(d => d.UserGroups).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserUserGroup",
                    r => r.HasOne<UserGroup>().WithMany()
                        .HasForeignKey("UserGroupId")
                        .HasConstraintName("FK__User_User__UserG__2DE6D218"),
                    l => l.HasOne<User>().WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__User_User__UserI__2CF2ADDF"),
                    j =>
                    {
                        j.HasKey("UserId", "UserGroupId").HasName("PK__User_Use__082D6A50C028EA0D");
                        j.ToTable("User_UserGroup", "furcha");
                    });
        });

        modelBuilder.Entity<UserBranch>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserBran__3214EC079155C74A");

            entity.ToTable("UserBranch", "furcha");

            entity.HasOne(d => d.Branch).WithMany(p => p.UserBranches)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserBranch_Branch");

            entity.HasOne(d => d.User).WithMany(p => p.UserBranches)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserBranch_User");
        });

        modelBuilder.Entity<UserEventLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserEven__3214EC0759244929");

            entity.ToTable("UserEventLog", "furcha");
        });

        modelBuilder.Entity<UserGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserGrou__3214EC07F79DB631");

            entity.ToTable("UserGroup", "furcha");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserGroupBranch>(entity =>
        {
            entity.HasKey(e => new { e.UserGroupId, e.BranchId }).HasName("PK__UserGrou__B04CE33CEC3669F9");

            entity.ToTable("UserGroup_Branch", "furcha");

            entity.HasOne(d => d.UserGroup).WithMany(p => p.UserGroupBranches)
                .HasForeignKey(d => d.UserGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupBranch_UserGroup");
        });

        modelBuilder.Entity<UserGroupLocker>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserGrou__3214EC07CEDD27BE");

            entity.ToTable("UserGroup_Locker", "furcha");

            entity.HasOne(d => d.Locker).WithMany(p => p.UserGroupLockers)
                .HasForeignKey(d => d.LockerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupLocker_Locker");

            entity.HasOne(d => d.UserGroup).WithMany(p => p.UserGroupLockers)
                .HasForeignKey(d => d.UserGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGroupLocker_UserGroup");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}