// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class LockerGroup
{
    public int Id { get; set; }

    public int? BranchId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<BrainModule> BrainModules { get; set; } = new List<BrainModule>();

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Locker> Lockers { get; set; } = new List<Locker>();
}