// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Locker
{
    public int Id { get; set; }

    public string PasswordHash { get; set; }

    public int? IsActive { get; set; }

    public int? IsOpen { get; set; }

    public int? LockerStatus { get; set; }

    public decimal? Number { get; set; }

    public int? BrainId { get; set; }

    public int? LockerType { get; set; }

    public int? ExternalId { get; set; }

    public bool IsDeleted { get; set; }

    public int? ReaderGroupId { get; set; }

    public virtual BrainModule Brain { get; set; }

    public virtual LockerType LockerTypeNavigation { get; set; }

    public virtual ICollection<UserGroupLocker> UserGroupLockers { get; set; } = new List<UserGroupLocker>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}