// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Locker
{
    public int Id { get; set; }

    public string LockerType { get; set; }

    public string PasswordHash { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsOpen { get; set; }

    public int? LockerStatus { get; set; }

    public int? GroupId { get; set; }

    public decimal? Number { get; set; }

    public int? BranchId { get; set; }

    public int? BrainId { get; set; }

    public virtual LockerGroup Group { get; set; }

    public virtual ICollection<UserGroupLocker> UserGroupLockers { get; set; } = new List<UserGroupLocker>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}