// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class Permission
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? ObjectTypeId { get; set; }

    public virtual ICollection<AdminPermission> AdminPermissions { get; set; } = new List<AdminPermission>();

    public virtual ObjectType ObjectType { get; set; }

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}