// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class SyncTask
{
    public long Id { get; set; }

    public Guid AccountUid { get; set; }

    public string BrainUid { get; set; }

    public int CommandType { get; set; }

    public byte Operation { get; set; }

    public string EntityType { get; set; }

    public int? EntityId { get; set; }

    public string Payload { get; set; }

    public byte Status { get; set; }

    public int Attempts { get; set; }

    public int MaxAttempts { get; set; }

    public DateTime NextAttemptAt { get; set; }

    public string LastError { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? SentAt { get; set; }

    public DateTime? AckedAt { get; set; }
}