// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class UserEventLog
{
    public int Id { get; set; }

    public int LockerId { get; set; }

    public int? CardIdId { get; set; }

    public int Action { get; set; }

    public string LockerStateAfter { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UserId { get; set; }
}