// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class UserGroup
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? CompanyId { get; set; }

    public int? State { get; set; }

    public virtual ICollection<UserGroupBranch> UserGroupBranches { get; set; } = new List<UserGroupBranch>();

    public virtual ICollection<UserGroupLocker> UserGroupLockers { get; set; } = new List<UserGroupLocker>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}