// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class UserGroupLocker
{
    public int Id { get; set; }

    public int UserGroupId { get; set; }

    public int LockerId { get; set; }

    public virtual Locker Locker { get; set; }

    public virtual UserGroup UserGroup { get; set; }
}