// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FurchaDAL.Models;

public partial class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CompanyId { get; set; }

    public int State { get; set; }

    public byte? IsMqtt { get; set; }

    public DateTime? ActiveFrom { get; set; }

    public DateTime? ActiveTo { get; set; }

    public virtual ICollection<Administrator> Administrators { get; set; } = new List<Administrator>();

    public virtual ICollection<Card> Cards { get; set; } = new List<Card>();

    public virtual ICollection<UserBranch> UserBranches { get; set; } = new List<UserBranch>();

    public virtual ICollection<Locker> Lockers { get; set; } = new List<Locker>();

    public virtual ICollection<UserGroup> UserGroups { get; set; } = new List<UserGroup>();
}