<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Database\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="HtmlSanitizer" Version="7.1.488" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>

</Project>
